//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historicos
    {
        public int ano { get; set; }
        public int semestre { get; set; }
        public int id_aluno { get; set; }
        public int id_disc { get; set; }
        public bool situacao { get; set; }
        public double media { get; set; }
        public int faltas { get; set; }
    
        public virtual Alunos Alunos { get; set; }
        public virtual Disciplinas Disciplinas { get; set; }
        public virtual Periodos_Letivos Periodos_Letivos { get; set; }
    }
}
