//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriz
    {
        public int id_disc { get; set; }
        public int id_curso { get; set; }
        public int periodo { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Disciplina Disciplina { get; set; }
    }
}
