//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcadControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public int ano { get; set; }
        public int semestre { get; set; }
        public int id_disc { get; set; }
        public int vagas { get; set; }
        public Nullable<int> id_prof { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Periodo_Letivo Periodo_Letivo { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
